
language: c
sudo: required
dist: trusty
install: make
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential
  - sudo apt-get install libatlas-base-dev
  
